# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee02ff3a7f23b5d9925508e65143613ec6fee5b7a496a96ad61fe4725f431e7120c25e1fa0d967555a832855223552d9b23a69ca6d58d5759e90c86042e4154b

test:
  secret_key_base: f4470b3a79179a4cef707750ec441aed296ed4de4a6ae67c8fd1d09a57a060d3d9a5a5ff7bbcae1e28c3f702029314fd55787d5b9bf74d94c9cf239c97b8678a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
